### ISSUE TITLE
TypeError: worthless_callback() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by dmdm** [tomlikestorock/pyramid_openid#4]
This error occurs when I try to login (with a Google account) on my published website. On my devel site on localhost, no error occurs and login succeeds.
Without digging to deep into the code, process_provider_response() on one occasion (which?) calls worthless_callback().
The call uses 3 params: context, request, success_dict, but worthless is missing the context param.

Maybe 

def worthless_callback(context, request, success_dict):
    pass

solves it

Cheers, Dirk

**Comment by tomlikestorock** [comment]
Hey dmdm, thanks for the heads up. Added a third parameter to worthless_callback, but don't have time to test it (I don't really use this - I use velruse instead (https://github.com/bbangert/velruse). Anyways, hope the works for you, if it doesn't feel free to send me a pull request.

**Comment by dmdm** [comment]
Hi tom, thanks for the update. It solves the TypeError, frankly however, it was me who caused the problem in the first place: forgot to put the config into production.ini, aye.
Had to look closer at your code. That worthless callback, what is it good for? It only gets called when no callback is configured. And that, instead of raising an exception, confused me.
Is it sensible to not have a callback? If it is missing, the original app has no idea whether the login was successful or not. Why not consider this an error?
If you agree with me, I can change the code and send you a pull request.
By the way, I like your small lib. Works perfectly for me now.
----EDIT
(Conversation in the attic:
- "That worthless callback, what is it good for?"
- "For nothing. That's why it is called `worthless`.'
  )
